language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: gh-pages